### ISSUE TITLE
Remove FTP drop from UI

### ISSUE THREAD

**Issue by vladimirg** [berman-lab/ymap#22]
Reverse-commit the original FTP drop commits?

**Comment by ghost** [comment]
Deployed on QC

**Sum up of commits related to the removing of the features and the files:**

 removed /register.php - we use user.register.php, /user.login.php - w…  …          8a8c998
 Revert "Merge branch 'Feature__Add-FTP-dropbox-file-access'"  …          eccbdb7
 removed uploder.4.php irrelevant since it was restored while revertin…  …          d0946a0
removed FTP folder          5ed8d40
removed FTP folder creation from user.register_server.php           c8ec1a2
removed double chomd in line 34 creation from user.register_server.php          9a3c49d
remove FTP_drop folder remove for user.delete_server.php            84e7336
panel.manageDataset.php to work again with variables            ed2cebf 
realign indentation in panel.manage.Dataset.php         99f95f5
add \n to line 14 in process_input_files.php - was removed during the…  …           4da7055
changed $dir in line 14 to be the same as before the revert of FTP          2a2b73d

**commits that are related to the FTP feature:** 

**commits that were reverted:**
f4ff9b6062cb36bf0934f432a3d8eadb84bbefb6 - the last commit related to FTP, removed almost the entire feature
75a21c2c330b947e97b03419028a18aa120dbad0 - remove FTP directory creation for user from user.register_server.php.
a5e05be6fd53b50e4b604b76c1f45ee47810d901 - remove FTP directory removal from user deletion, the commit wasn’t actually reverted since it contained changes to .gitignore so only the changes to user.delete_server.php were committed

**commits that were not reverted**
d9264023c9027affe329ce9fda0618d4afdd6835 - irrelevant commit, changes comment in a section related to FTP drop that were already removed
ab06d3b53f7fb6b3c264680a7a03cf46f09558fe - commits related to file_selection, these files were already removed with the commit of the entire feature
5738d4831047a99caa1dfbf15dc7431f56f04db1 - the commit changes scripts_seqModules/scripts_WGseq/CNV_SNP_hapmap_v4_RedGreen.m which doesn’t seem related to the ftp,  also the file has been committed multiple times with changes unrelated to FTP so no need to revert file
341f8cac898f245768c1cec14a260dbc0b7037d4 - contains changes to multiple files that used to handle FTP drop (both UI and Server side), all of the changes were reverted using the last commit related to FTP, also has minor indentation changes that doesn’t need to be reverted.
679dcb5bcb857d389a8c05ed2d35d029671ed6d9 - contain updates only to .gitigonre file, since the current file is updated no revert is needed

also files that were removed since they are no longer relevant
/register.php - we use user.register.php, 
/user.login.php - we use panel.user
/register_server.php - we use user.register_server.php
