### ISSUE TITLE
"Fat" CNV bars in lovelace

### ISSUE THREAD

**Issue by vladimirg** [berman-lab/ymap#33]
Ymap's CNV bars in lovelace are too bold, and make the CNVs and the SNPs hard to read in the linear mode. This doesn't seem to happen on non-lovelace installations.

This was raised with Darren previously, transcript:

"There aren't any targeted configuration differences in the matlab installed on lovlace, but there potentially are differences in how matlab chooses its rendering engine based on hardware /software availability.

I had previously run into a really annoying error in relation to this.  I had originally used some transparency features to construct the figures...  but when matlab was running on the server (or in any console-only mode it turned out), it would crash hard any time it tried to use transparency in figures.

I bring this up because I wonder if it may be the root cause to the rendering issue you describe."

**Comment by vladimirg** [comment]
Especially pronounced with ddRADseq data, but also an issue with WGS.

**Comment by GuyKha** [comment]
Seems to be a problem with the version of matlab (2012b on lovelace).
Works fine both on mac with matlab 2014a and Ubuntu 16.04 with matlab 2015a.
Also checked and all of the properties seems to be the same, the problem appears in all figures generated by code (I have generated a figure on lovelace and on ubuntu with matlab 2015a and there were size differences). 
I have sent a [question on matlab forums](http://www.mathworks.com/matlabcentral/answers/300460-saving-figure-issue-matlab-2012b), hopefully the will help.

**Comment by ghost** [comment]
I have found a fix for this problem, the problem is the in versions prior to matlab R2014b under "nodisplay" matlab use Ghostscript to generate output  instead of using the drivers built into MATLAB, as a result matlab uses the default DPI which is 72DPI. ([more info](http://www.mathworks.com/matlabcentral/answers/282377-adjust-the-resolution-of-png-plot-image-on-a-remote-terminal?s_tid=answers_rc1-1_p1))
so we have two options:
1. calculating the DPI manually using the following code and adjusting figure sizes according to the DPI (to find out the DPI we can use [this code](https://www.mathworks.com/matlabcentral/answers/100792-in-matlab-how-do-i-obtain-information-about-my-screen-resolution-and-screen-size))
2. upgrading matlab on lovelace.

**Comment by vladimirg** [comment]
Excellent! Let's try out the fix to make sure it works, but let's not deploy it yet - if lovelace is going to be updated soon anyway and they'll upgrade Matlab, then it should automatically solve our issue.

However, we do need to worry about the EPS issues we see on the newer Matlabs. Can you look into it, please?

**Comment by ghost** [comment]
I have checked and the EPS files work fine.
As for the DPI changing the size in the QC environment did result in a better result, yet the file size is still lower then a file created in later versions of matlab (2014b and on). 
If the matlab version in lovelace will be updated it will solve the problem otherwise we can change the sizes of all of the figures according to the DPI.

**Comment by vladimirg** [comment]
Related to commit b2d55f18bf4ceb119e3d5604ce8c06b1107779f1, which adds support for Matlab 2016a.
